version: "3.7"

services:
  oltp:
    image: postgres
    environment:
      POSTGRES_DB: 'sales_oltp'
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - 54320:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "sales_oltp"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  
  dagster-dbt:
    build:
      context: .
      dockerfile: ./dagster-dbt/Dockerfile
    restart: always
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        DAGSTER_HOME: /dagster-dbt/postcard_company_dm
    volumes:
        - ./dagster-dbt/postcard_company_dm:/dagster-dbt/postcard_company_dm
    ports:
        - "3000:3000"
    command: dagit -h 0.0.0.0
    
 